// app/api/products/route.ts
import { supabase } from "../../../../../lib/supabase";

import { NextRequest } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { name, description, price, calories, category, image_url, is_veg } =
      body;

    // Validate required fields
    if (!name || !price || !category) {
      return Response.json(
        {
          error: "Missing required fields: name, price, category",
        },
        { status: 400 },
      );
    }

    // Validate category
    const validCategories = ["hot", "cold", "sides", "merchandise"];
    if (!validCategories.includes(category)) {
      return Response.json(
        {
          error: `Invalid category. Must be one of: ${validCategories.join(
            ", ",
          )}`,
        },
        { status: 400 },
      );
    }

    // Insert product (ID will be auto-generated by trigger)
    const { data, error } = await supabase
      .from("products")
      .insert({
        name,
        description,
        price,
        calories,
        category,
        image_url,
        is_veg: is_veg ?? true,
      })
      .select()
      .single();

    if (error) {
      return Response.json({ error: error.message }, { status: 500 });
    }

    return Response.json(
      {
        success: true,
        product: data,
      },
      { status: 201 },
    );
  } catch (error) {
    return Response.json(
      {
        error: "Failed to create product",
      },
      { status: 500 },
    );
  }
}
