import { supabase } from "../../../../../lib/supabase";

import { NextRequest } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      name,
      description,
      price,
      calories,
      category,
      image,
      isVeg,
      isAvailable,
    } = body;

    // Validate required fields
    if (!name || !price || !category) {
      return Response.json(
        {
          error: "Missing required fields: name, price, category",
        },
        { status: 400 },
      );
    }

    // Insert product (ID will be auto-generated by trigger)
    const { data, error } = await supabase
      .from("products")
      .insert({
        category,
        name,
        description,
        price,
        calories,
        image,
        is_veg: isVeg ?? true,
        is_available: isAvailable ?? true,
      })
      .select()
      .single();

    if (error) {
      return Response.json({ error: error.message }, { status: 500 });
    }

    return Response.json(
      {
        success: true,
        product: data,
      },
      { status: 201 },
    );
  } catch (error) {
    return Response.json(
      {
        error: "Failed to create product",
      },
      { status: 500 },
    );
  }
}
